#Collecte les données en fonction d'une liste de tciker

#Si les données ne sont pas disponibles (df = empty) -> on supprime l'actif
#On prend les actifs du data frame indice

#Récupération des données de rendements
import pandas as pd
import yfinance as yf

def data_collector(df_data: pd.DataFrame, start: str, end: str, dict_tickers: dict = None) -> pd.DataFrame:
    """
    Collecte les données de rendements pour les actifs listés dans le DataFrame df_data 
    (typiquement issu de la classe indice_score). Pour chaque actif, la fonction télécharge 
    les données de prix sur Yahoo Finance entre les dates 'start' et 'end', calcule les 
    rendements quotidiens via la méthode pct_change(), et retourne un DataFrame des rendements.
    
    Si dict_tickers n'est pas fourni, un dictionnaire de correspondance actif -> ticker 
    par défaut est utilisé.
    
    Étapes :
        1. Si dict_tickers est None, alors on définit un dictionnaire par défaut.
        2. On extrait la première colonne de df_data (les noms d'actifs) et on supprime les espaces inutiles.
        3. Pour chaque actif, on récupère le ticker correspondant et on télécharge les données via yfinance.
        4. Si aucune donnée n'est trouvée (data.empty), l'actif est ignoré.
        5. Si la colonne 'Close' est présente dans les données, on l'utilise pour calculer 
           les rendements quotidiens (pct_change()). Si 'Close' contient plusieurs colonnes, 
           seule la première est utilisée.
        6. Enfin, le DataFrame final est nettoyé (dropna) des valeurs manquantes et retourné.
    
    Retour :
        pd.DataFrame: DataFrame contenant, pour chaque actif réussi, les rendements quotidiens.
    """
    #pour nous ce sera df_data=indice.actifs de la classe indice_score
    if dict_tickers is None:
        dict_tickers = {
        "Amadeus IT Group SA": "AMS.MC",
        "Infosys Ltd": "INFY",
        "Microsoft Corp": "MSFT",
        "Amadeus IT Group SA": "AMS.MC",  
        "Tencent Holdings Ltd": "0700.HK",
        "Wipro Ltd": "WIT",
        "SK Inc": "034730.KS",
        "SAP SE": "SAP",
        "Quadient SA": "QDT.PA",
        "NEC Corp": "6701.T",
        "KBR Inc": "KBR",
        "Kakao Corp": "035720.KS",
        "RELX PLC": "RELX",
        "Vakrangee Limited": "VAKRANGEE.NS",
        "Naver Corp": "035420.KS",
        "Fujitsu Ltd": "6702.T",
        "Solutions 30 SE": "S30.PA",
        "HCL Technologies Ltd": "HCLTECH.NS",
        "Accenture PLC": "ACN",
        "Kyndryl Holdings Inc": "KD",
        "Alphabet Inc": "GOOGL",
        "Autodesk Inc": "ADSK",
        "Delivery Hero SE": "DHER.DE",
        "Mastercard Inc": "MA",
        "Uber Technologies Inc": "UBER",
        "Persistent Systems Ltd": "PERSISTENT.NS",
        "Indra Sistemas SA": "IDR.MC",
        "Kinaxis Inc": "KX",
        "AwanBiru Technology Bhd": "AWB.KL",
        "Mastek Ltd": "MASTEK.NS",
        "Totvs SA": "TOTS3.SA",
        "Knowit AB (publ)": "KNOWIT.ST",
        "Insight Enterprises Inc": "NSIT",
        "Cadence Design Systems Inc": "CDNS",
        "ASGN Inc": "ASGN",
        "Sopra Steria Group SA": "SOP.PA",
        "Open Text Corp": "OTEX",
        "Kingsoft Cloud Holdings Ltd": "KCWS",
        "Logo Yazilim Sanayi ve Ticaret AS": "LOGO.IS",
        "Atea ASA": "ATEA.OL",
        "Verisk Analytics Inc": "VRSK",
        "SCSK Corp": "9023.T",
        "Science Applications International Corp": "SAIC",
        "Gen Digital Inc": "GEN",
        "Kingsoft Corporation Ltd": "KC",
        "Cyient Ltd": "CYIENT",
        "Kontron AG": "KNTR.DE",
        "Samsung SDS Co Ltd": "018260.KS",
        "Temenos AG": "TEMN.SW",
        "Teradata Corp": "TDC",
        "Zalando SE": "ZAL.DE",
        "TeamViewer SE": "TMV.DE",
        "NTT Data Group Corp": "9613.T",
        "Amdocs Ltd": "DOX",
        "Cognizant Technology Solutions Corp": "CTSH",
        "Gartner Inc": "IT",
        "Dayforce Inc": "DFIN",
        "Booz Allen Hamilton Holding Corp": "BAH",
        "International Business Machines Corp": "IBM",
        "Route Mobile Ltd": "ROUTE.NS",
        "Oracle Financial Services Software Ltd": "OFSS.NS",
        "SoftwareOne Holding Ltd": "SWON.SW",
        "G-bits Network Technology Xiamen Co Ltd": "688098.SS",
        "PTC Inc": "PTC",
        "Tata Consultancy Services Ltd": "TCS.NS",
        "Computacenter PLC": "CCC.L",
        "Atos SE": "ATO.PA",
        "ServiceNow Inc": "NOW",
        "NARI Technology Co Ltd": "600406.SS",
        "Tata Elxsi Ltd": "TATAELXSI.NS",
        "eBay Inc": "EBAY",
        "Modern Times Group MTG AB": "MTG.ST",
        "China TransInfo Technology Co Ltd": "600026.SS",
        "Info Edge (India) Ltd": "NAUKRI.NS",
        "Gamma Communications PLC": "GAMMA.L",
        "Globant SA": "GLOB",
        "Reply SpA": "REY.MI",
        "Hightech Payment Systems SA": "HPS.PA",
        "Netmarble Corp": "251270.KQ",
        "Electronic Arts Inc": "EA",
        "CACI International Inc": "CACI",
        "Nelly Group AB (publ)": "NELLY.ST",
        "QBeyond AG": "QBAG.DE",
        "TIS Inc": "TISI",
        "Check Point Software Technologies Ltd": "CHKP",
        "B&S Group SA": "BSG.PA",
        "Tech Mahindra Ltd": "TECHM.NS",
        "Alten SA": "ATE.PA",
        "Scout24 SE": "G24.DE",
        "Adobe Inc": "ADBE",
        "CoStar Group Inc": "CSGP",
        "CSG Systems International Inc": "CSGS",
        "91APP Inc": "9166.TW",
        "NetEase Inc": "NTES",
        "TechnologyOne Ltd": "TNE.AX",
        "Eternal Ltd": "ETR.L",
        "Glodon Co Ltd": "002410.SZ",
        "Endava PLC": "DAVA.L",
        "Newgen Software Technologies Ltd": "NEWG.NS",
        "F5 Inc": "FFIV",
        "SK Square Co Ltd": "041510.KS",
        "Automatic Data Processing Inc": "ADP",
        "Longshine Technology Group Co Ltd": "300211.SZ",
        "DXC Technology Co": "DXC",
        "Akamai Technologies Inc": "AKAM",
        "HubSpot Inc": "HUBS",
        "TTEC Holdings Inc": "TTEC",
        "Epam Systems Inc": "EPAM",
        "Ecloudvalley Digital Technology Co Ltd": "688168.SS",
        "Fuji Soft Inc": "6704.T",
        "Ziff Davis Inc": "ZD",
        "Rightmove PLC": "RMV.L",
        "Salesforce Inc": "CRM",
        "Netcompany Group A/S": "NETC-A.CO",
        "Atlassian Corp": "TEAM",
        "Mphasis Ltd": "MPHASIS.NS",
        "Tyler Technologies Inc": "TYL",
        "Bechtle AG": "BC8.DE",
        "Beijing E-hualu Information Technology Co Ltd": "UNKNOWN",
        "Meituan": "3690.HK",
        "Kingdee International Software Group Co Ltd": "0268.HK",
        "Askul Corp": "ASKUL.T",
        "Capgemini SE": "CAP.PA",
        "Progress Software Corp": "PRGS",
        "Digia Oyj": "DIGIA.HE",
        "Kakao Games Corp": "293490.KQ",
        "Enea AB": "ENEA-B.ST",
        "East Buy Holding Ltd": "EBHL",
        "Bumble Inc": "BMBL",
        "Sonata Software Ltd": "SONATN.NS",
        "CE Info Systems Ltd": "CEINF.NS",
        "VNET Group Inc": "VNET",
        "Perfect World Co Ltd": "002624.SZ",
        "Cyberark Software Ltd": "CYBR",
        "Beijing United Information Technology Co Ltd": "UNKNOWN",
        "NCSoft Corp": "036570.KS",
        "Ubisoft Entertainment SA": "UBI.PA",
        "Dassault Systemes SE": "DSY.PA",
        "Better Collective A/S": "BET.CO",
        "Data#3 Ltd": "DATA3.L",
        "Cancom SE": "COK.DE",
        "Cloudflare Inc": "NET",
        "Datatec Ltd": "DTC.L",
        "Nomura Research Institute Ltd": "4307.T",
        "Addnode Group AB (publ)": "ADDN.ST",
        "Happiest Minds Technologies Ltd": "HAPP.NS",
        "Netscout Systems Inc": "NTCT",
        "Biprogy Inc": "BIPR",
        "Blackbaud Inc": "BLKB",
        "LTIMindtree Ltd": "LTIM.NS",
        "Otsuka Corp": "4578.T",
        "Nice Ltd": "NICE",
        "Meta Platforms Inc": "META",
        "CGI Inc": "GIB.A.TO",
        "Schrodinger Inc": "SDGR",
        "Dolby Laboratories Inc": "DLB",
        "GFT Technologies SE": "GFT.DE",
        "Nemetschek SE": "NEM.DE",
        "IGG Inc": "IGG",
        "Conduent Inc": "CNDT",
        "adesso SE": "ADN.DE",
        "Posco DX Co Ltd": "006490.KS",
        "Stillfront Group AB (publ)": "SF.ST",
        "Auto Trader Group PLC": "AUTO.L",
        "Copart Inc": "CPRT",
        "Black Box Ltd": "BBT",
        "Box Inc": "BOX",
        "Xero Ltd": "XRO.AX",
        "Trimble Inc": "TRMB",
        "VeriSign, Inc": "VRSN",
        "Hitit Bilgisayar Hizmetleri AS": "HITTL.IS",
        "GoDaddy Inc": "GDDY",
        "Oracle Corp Japan": "7733.T",
        "Prosus NV": "PRX.AS",
        "Zensar Technologies Ltd": "ZENSAR.NS",
        "Systex Corp": "2498.TW",
        "Commvault Systems Inc": "CVLT",
        "Alight Inc": "ALIT",
        "Lectra SA": "LTR.PA",
        "Rakuten Group Inc": "4755.T",
        "Roper Technologies Inc": "ROP",
        "Fortinet Inc": "FTNT",
        "ANSYS Inc": "ANSS",
        "LY Corp": "LY",
        "Jack Henry & Associates Inc": "JKHY",
        "Crayon Group Holding ASA": "CRAYON.OL",
        "OptimizeRx Corp": "OPRX",
        "iFLYTEK Co Ltd": "002230.SZ",
        "FinVolution Group": "FVOL",
        "Ework Group AB": "EWORK.ST",
        "Pros Holdings Inc": "PROS",
        "Fiverr International Ltd": "FVRR",
        "Wangsu Science & Technology Co Ltd": "002305.SZ",
        "Olo Inc": "OLO",
        "Pegasystems Inc": "PEGA",
        "CAR Group Ltd": "CAR",
        "Chinasoft International Ltd": "0998.HK",
        "Birlasoft Ltd": "BIRLASOFT.NS",
        "Appen Ltd": "APX.AX",
        "Alibaba Group Holding Ltd": "BABA",
        "Wirtualna Polska Holding SA": "WPG.WA",
        "MFEC PCL": "MFEC.NS",
        "Dropbox Inc": "DBX",
        "Alithya Group Inc": "ALYA.TO",
        "WiseTech Global Ltd": "WTC.AX",
        "Ovh Groupe SA": "OVH.PA",
        "Vipshop Holdings Ltd": "VIPS",
        "MercadoLibre Inc": "MELI",
        "My EG Services Bhd": "MYEG.KL",
        "Global Business Travel Group Inc": "GBTG",
        "Shanghai Baosight Software Co Ltd": "600536.SS",
        "Serko Ltd": "SERK.AX",
        "NEXTDC Ltd": "NDC.AX",
        "Tietoevry Oyj": "TIETO.HE",
        "PEXA Group Ltd": "PEXA.AX",
        "Krafton Inc": "259960.KS",
        "Topsec Technologies Group Inc": "TOPSEC.KS",
        "Trifork Group AG": "TRIF.L",
        "Descartes Systems Group Inc": "DSG",
        "Guidewire Software Inc": "GWRE",
        "Catena Media PLC": "CAT.L",
        "Yelp Inc": "YELP",
        "FDM Group (Holdings) PLC": "FDM.L",
        "Visa Inc": "V",
        "Spotify Technology SA": "SPOT",
        "secunet Security Networks AG": "SEC1.DE",
        "Baidu Inc": "BIDU",
        "GoTo Gojek Tokopedia PT Tbk": "GOTO.JK",
        "Baozun Inc": "BZUN",
        "Lightspeed Commerce Inc": "LSPD.TO",
        "Link Mobility Group Holding ASA": "LMO.OL",
        "Mercari Inc": "4385.T",
        "Domain Holdings Australia Ltd": "DHG.AX",
        "Verint Systems Inc": "VRNT",
        "Lastminute.com NV": "LMN.AS",
        "BHG Group AB": "BHG.ST",
        "Verve Group SE": "VERV.DE",
        "Twilio Inc": "TWLO",
        "RM PLC": "RM.L",
        "Palo Alto Networks Inc": "PANW",
        "Information Services Group Inc": "III",
        "NCC Group PLC": "NCC.L",
        "Just Eat Takeaway.com NV": "JET.L",
        "MONY Group PLC": "MONY.L",
        "R Systems International Ltd": "RSYS.NS",
        "Kakaku.com Inc": "4755.T",
        "PearlAbyss Corp": "263750.KQ",
        "ThredUp Inc": "TDUP",
        "Sirma Group Holding AD": "SIRMA.BV",
        "Konami Group Corp": "9766.T",
        "Zoom Communications Inc": "ZM",
        "Nazara Technologies Ltd": "NAZARA.NS",
        "Healthequity Inc": "HQY",
        "Qi An Xin Technology Group Inc": "688119.SS",
        "Sonda SA": "SONDA.SN",
        "Sage Group PLC": "SGE.L",
        "Nutanix Inc": "NTNX",
        "Workiva Inc": "WK",
        "Coforge Ltd": "COFORGE.NS",
        "iomart group PLC": "IOM.L",
        "Tracsis PLC": "TRCS.L",
        "NCR Voyix Corp": "NCR",
        "Softcat PLC": "SFT.L",
        "Hinduja Global Solutions Ltd": "HGS.NS",
        "Rimini Street Inc": "RMST",
        "Doximity Inc": "DOXI",
        "NHN Corp": "181710.KQ",
        "Asana Inc": "ASAN",
        "M3 Inc": "2413.T",
        "iSoftStone Information Technology Group Co Ltd": "002641.SZ",
        "GB Group PLC": "GBG.L",
        "Asseco Poland SA": "ACP.WA",
        "Dynatrace Inc": "DT",
        "Latent View Analytics Ltd": "LVA.NS",
        "Mekdam Holding Group QPSC": "Mekdam",
        "Readly International AB (publ)": "RDLY.ST",
        "THG PLC": "THG.L",
        "Tinexta SpA": "TIX.MI",
        "NNIT A/S": "NNIT.CO",
        "Dataprep Holdings Bhd": "DHP.KL",
        "37 Interactive Entertainment Network Technology Group Co Ltd": "3710.HK",
        "DLH Holdings Corp": "DLHC",
        "Trend Micro Inc": "TMICY",
        "Kainos Group PLC": "KNS.L",
        "Beijing Sinnet Technology Co Ltd": "300313.SZ",
        "MongoDB Inc": "MDB",
        "KPIT Technologies Ltd": "KPIT.NS",
        "ePlus inc": "PLUS",
        "Baltic Classifieds Group PLC": "BALT.L",
        "NexG Bhd": "NEXG.KL",
        "Bilibili Inc": "BILI",
        "Workday Inc": "WDAY",
        "Hemnet Group AB (publ)": "HEM.ST",
        "SoundThinking Inc": "SoundThinking",
        "Gofore Oyj": "GOFORE.HE",
        "Capcom Co Ltd": "9697.T",
        "GDS Holdings Ltd": "GDS",
        "AUTO1 Group SE": "AG1.DE",
        "Grab Holdings Ltd": "GRAB",
        "Siteminder Ltd": "SITM.AX",
        "Vertex Inc": "VERX",
        "Hostelworld Group PLC": "HOST.L",
        "SenseTime Group Inc": "0020.HK",
        "China National Software & Service Co Ltd": "603698.SS",
        "Cambricon Technologies Corp Ltd": "688256.SS",
        "IVU Traffic Technologies AG": "IVU.DE",
        "Ibex Ltd": "IBEX.L",
        "DeNA Co Ltd": "2432.T",
        "Nuix Ltd": "NULX",
        "Definitive Healthcare Corp": "DHHC",
        "Giant Network Group Co Ltd": "8038.HK",
        "Xometry Inc": "XMT",
        "Oracle Corp": "ORCL",
        "Solocal Group SA": "SOLB.PA",
        "Paycom Software Inc": "PAYC",
        "EROAD Ltd": "ERD.AX",
        "Take-Two Interactive Software Inc": "TTWO",
        "DoorDash Inc": "DASH",
        "Rapid7 Inc": "RPD",
        "Match Group Inc": "MTCH",
        "Thunder Software Technology Co Ltd": "ThunderSoft",
        "WeMade Co Ltd": "WEMADE",
        "CompuGroup Medical SE & Co KgaA": "CGM.DE",
        "Udemy Inc": "UDMY",
        "New Work SE": "NEWW.DE",
        "360 Security Technology Inc": "360ST",
        "Hundsun Technologies Inc": "600570.SS",
        "Infomedia Ltd": "IFML.L",
        "LG Corp": "003550.KS",
        "Indiamart Intermesh Ltd": "INDIAMART.NS",
        "Claranova SE": "CLRN.PA",
        "Dada Nexus Ltd": "DADA.NS",
        "Jfrog Ltd": "FROG",
        "Econocom Group SE": "ECO.PA",
        "iOCO Ltd": "iOCO",
        "Elastic NV": "ESTC",
        "Phreesia Inc": "PHR",
        "HealthStream Inc": "HSTM",
        "Money Forward Inc": "3994.T",
        "Sprout Social Inc": "SPT.SW",
        "Youzan Technology Ltd": "YZ",
        "Beijing Teamsun Technology Co Ltd": "000000.SZ",
        "Mannai Corporation QPSC": "MANNAI",
        "Vista Group International Ltd": "VGI.AX",
        "Auction Technology Group PLC": "ATG.L",
        "Alma Media Oyj": "ALMA.HE",
        "Coursera Inc": "COUR",
        "Dentsu Soken Inc": "4324.T",
        "Lime Technologies AB (publ)": "LIME.ST",
        "Porch Group Inc": "PRGN",
        "Innodata Inc": "INOD",
        "SolarWinds Corp": "SWI",
        "GDEV Inc": "GDEV",
        "DHC Software Co Ltd": "002536.SZ",
        "Gree Holdings Inc": "000651.SZ",
        "Elm Company SJSC": "ELM",
        "N-Able Inc": "NABL",
        "ON24 Inc": "ON24",
        "Hyundai Autoever Corp": "086280.KQ",
        "Allot Ltd": "ALLT",
        "WithSecure Oyj": "WSOY.ST",
        "Redcentric PLC": "RED.L",
        "Articore Group Ltd": "ARTI.L",
        "All for One Group SE": "AF1.DE",
        "RingCentral Inc": "RNG",
        "Embracer Group AB": "EMBRAC-B.ST",
        "Jumia Technologies AG": "JMIA",
        "Sabre Corp": "SABR",
        "Square Enix Holdings Co Ltd": "9684.T",
        "TravelSky Technology Ltd": "2607.HK",
        "Toast Inc": "TOST",
        "Fair Isaac Corp": "FICO",
        "REA Group Ltd": "REA.AX",
        "Tuya Inc": "TUYA",
        "CENIT AG": "CENIT",
        "Sinch AB (publ)": "SINCH.ST",
        "TELUS International (CDA) Inc": "TINT",
        "Digital Garage Inc": "6415.T",
        "Aubay SA": "AUB.PA",
        "Agilysys Inc": "AGYS",
        "Weimob Inc": "300660.SZ",
        "PagerDuty Inc": "PD",
        "Nextdoor Holdings Inc": "NODK",
        "USS Co Ltd": "USS",
        "Beijing Kingsoft Office Software Inc": "Kingsoft",
        "WM Technology Inc": "WMTI",
        "Thunderful Group AB": "THUNDERFUL.ST",
        "Nexon Co Ltd": "3659.T",
        "Adeia Inc": "ADEIA",
        "Tanla Platforms Ltd": "TANLA.NS",
        "A10 Networks Inc": "ATEN",
        "NavInfo Co Ltd": "NAVINFO",
        "Yonyou Network Technology Co Ltd": "600588.SS",
        "Fubotv Inc": "FUBOTV",
        "Meitu Inc": "3690.HK",
        "IAC Inc": "IAC",
        "Deliveroo PLC": "DLR.L",
        "Zoominfo Technologies Inc": "ZI",
        "Inspired Entertainment Inc": "Inspired",
        "Zscaler Inc": "ZS",
        "Alarm.com Holdings Inc": "ALRM",
        "NanJi E-Commerce Co Ltd": "NJC",
        "Dubber Corp Ltd": "DUBB.L",
        "Nexus AG": "NEXUS",
        "MAG Interactive AB (publ)": "MAGI.ST",
        "Arabian Internet and Communications Services Company SJSC": "ARABI"
    }
    # Nettoyage et récupération des tickers à partir du DataFrame df_data
    tickers = [dict_tickers.get(str(ticker).strip(), str(ticker).strip()) for ticker in df_data.iloc[:, 0].tolist()]
    df_rendements = pd.DataFrame()

    # Boucle sur chaque ticker pour télécharger les données et calculer les rendements
    for ticker in tickers:
        try:
            data = yf.download(ticker, start=start, end=end, auto_adjust=True)
            print(f"{ticker} — Dimensions des données: {data.shape}, Colonnes: {list(data.columns)}")
            # Si aucune donnée n'est récupérée, on passe à l'actif suivant
            if data.empty:
                print(f"[!] Aucune donnée récupérée pour {ticker}")
                continue

            # Vérification de la présence de la colonne 'Close'
            if 'Close' in data.columns:
                close_data = data['Close']
                # Si 'Close' est un DataFrame à plusieurs colonnes, ne prendre que la première colonne
                if isinstance(close_data, pd.DataFrame) and close_data.shape[1] > 1:
                    close_data = close_data.iloc[:, 0]
                # Calcul des rendements quotidiens avec pct_change()
                df_rendements[ticker] = close_data.pct_change()
            else:
                print(f"[!] 'Close' non trouvé pour {ticker}")
        except Exception as e:
            print(f"[!] Erreur pour {ticker} : {e}")


    df_rendements.dropna(inplace=True)
    return df_rendements
